### PR TITLE
mixed content fix

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
@Mottie redone.

**Comment by Mottie** [comment]
Thanks!

**Comment by OmgImAlexis** [comment]
By the way this also has to be done on the gh-pages branch.

**Comment by Mottie** [comment]
Yes, I know... I usually don't push updates to gh-pages until I release a new version. With all the activity I am seeing so far this week, a new release won't be far off.

**Comment by OmgImAlexis** [comment]
Alright, just thought I'd mention it.

**Pull request merged**
