### PR TITLE
Fix jquery deprecations

### PR DESCRIPTION
**Pull request by venkatraj**
#### Reference Issues/PRs
None

#### What does this implement/fix? Explain your changes
Fixing the JQuery deprecation code 

#### Any other comments?
No

### CODE REVIEW

**Comment by Alexandermjos** [comment]
Any updates on this? I am also upgrading legacy app 🤣

**Comment by marcos-castrillo** [comment]
Same situation here

**Comment by Mottie** [comment]
I'll look into this over the weekend. Thanks for your patience.

**Comment by Mottie** [comment]
Sorry, this is taking longer than I thought... so much stuff to update!

**Comment by marcos-castrillo** [comment]
Thanks for taking care of this!

**Comment by elebitzero** [comment]
$.trim is another deprecated function that is not migrated in the PR yet.

> $.trim has been deprecated in jQuery 3.5; please use the native [String.prototype.trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) method instead. Unlike jQuery.trim, String.prototype.trim does not work with types other than strings (null, undefined, Number). Make sure that your code is compatible when migrating.

**Comment by nagyimre1980** [comment]
pls..... new verison... trhx

**Comment by nagyimre1980** [comment]
pls..... new verison... thx

**Comment by nagyimre1980** [comment]
deleting?? :(

**Comment by venkatraj** [comment]
@nagyimre1980 Sorry, we need to ship those changes in our software. All third party libraries are forked in our company account. Since I can't fork same repo from two places, I have to delete this, in order to fork our company repo and merge the changes.

May be our Lead Developer will create a PR with those changes.

**Comment by nagyimre1980** [comment]
NEW PR?

**Comment by rylanb** [comment]
Please do consider this, I don't want to go in and update the library for the bind/unbind/trim deprecation warnings I've been getting for months. Thank you if you can get to this! Thanks for the plugin, as well!

**Comment by DavidAnderson684** [comment]
This fork has the jQuery compatibility commits in it: https://github.com/DavidAnderson684/tablesorter/tree/master . If anyone wants to create a new PR on https://github.com/Mottie/tablesorter/ using those changes, then they are welcome.

**Comment by AviHafner** [comment]
Hi @DavidAnderson684 
On this site there are 2 customized files [https://www.admin.technion.ac.il/tablesorter-V3.1/](https://www.admin.technion.ac.il/tablesorter-V3.1/)
this version working with **Jquery 4**
its taking   from version of **tablesorter Version 2.31.3**
I would be very happy if you adopt the changes in this version and make them official.

**Comment by DavidAnderson684** [comment]
@AviHafner You're confusing me with someone else, I am not a committer for `Mottie/tablesorter`.

**Comment by kczx3** [comment]
So far these are all just deprecations however they all would prevent this library from functioning with jQuery 4.  I see a second beta release for jQuery 4 was released last month.  I don't think it is too farfetched to think that a final release for jQuery 4 could arrive by the end of the year.  Seeing that Mottie just committed a change that removes the `ie8` option from the gruntfile, it also isn't too crazy to think that this project could be updated to support only IE11.  However, the choice would have to be made if the supported jQuery versions could be reduced.  Seeing as this project hasn't had much in the way of fixes and enhancements in 4 years, I would support a major version bump that aligns with the move to only jQuery 4+ support.  Drastic fixes and enhancements in the future are probably not too likely so requiring folks on older jQuery 3 or less to use the 2.x version of tablesorter seems appropriate to me.  They probably won't miss out on much.

**Pull request closed without merging**
