### PR TITLE
Add `widgetRemoveEnd` event

### PR DESCRIPTION
**Pull request by Fohlen**
This PR introduces a `widgetRemoveEnd` event which can be quiet handy in the following set up

- one has a widget that is occasionally added and removed (depending on what table is sorted)
- the sort end event can happen after the widget has been removed and initialized
- this can result in the old table being used for the widget

=> using a `widgetRemoveEnd` event makes it possible to intercept the above behavoir.
Sorry for the big diff. It's only 2 lines actually, but `grunt` rewrote about 97%, if you need to know the exact changes, let me know.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @Fohlen!

I can add `?w=1` to the url to ignore all the whitespace changes...

1. Please put all my tabs back. I love my tabs!  
2. The testing function has this addition `assert.equal( ts, 'removeWidgetEnd fired' );`. I didn't try this, but `ts` is the variable containing the tablesorter object `$.tablesorter`. I don't see how that could be equal.

**Comment by Fohlen** [comment]
Hey @Mottie 
1. That must have been Atom! If you urge, I can convert spaces -> tabs again
2. uh. I'm not really introduced into QUnit and didn't understand how it tests the events. However I verified that it works in Chrome. Mind updating the unit test?

**Comment by Mottie** [comment]
I think it might be easier for me to add this enhancement then... I'll get to it when I get some time, probably later this afternoon.

**Comment by Mottie** [comment]
Added in v2.29.0 - [see docs](https://mottie.github.io/tablesorter/docs/#widgetremoveend).

**Pull request closed without merging**
