### PR TITLE
Converted theme.less to theme.sass

### PR DESCRIPTION
**Pull request by HongPong**
I thought it might be handy to have theme.sass available instead, in case you are developing in sass.

### CODE REVIEW

**Comment by Mottie** [comment]
Awesome! Thanks a lot!

**Comment by HongPong** [comment]
I went a little too fast. These have to be set as mixins - i simplified things for my purposes. Other than that everything is pretty groovy.

/* zebra striping */
@mixin allRows {
	background-color: $bodyBackground;
	color: $bodyTextColor;
}
@mixin evenRows {
	background-color: lighten($headerBackground, 40%);
	color: $bodyTextColor;
}
@mixin oddRows {
	background-color: lighten($headerBackground, 20%);
}

/* hovered rows */
@mixin oddHovered {
	background-color: desaturate($headerBackground, 60%);
	color: $bodyTextColor;
}
@mixin evenHovered {
	background-color: lighten( desaturate($headerBackground, 60%), 10% );
	color: $bodyTextColor;
}

**Comment by Mottie** [comment]
Feel free to make the changes in the repo 😺

**Comment by Mottie** [comment]
Hey @HongPong!

I am seeing an error when I try to use this file - see http://beautifytools.com/scss-compiler.php - I haven't used SCSS much, so I would appreciate it if you could troubleshoot the problem.

Thanks!

**Pull request merged**
