### PR TITLE
Update widget-stickyHeaders.js

### PR DESCRIPTION
**Pull request by naduda**
BugFix for tables which have hidden columns.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @naduda!

Thanks for contributing! Can you please provide an example?

I have [this demo](http://jsfiddle.net/9hLref4s/) which uses the columnSelector widget with the stickyHeaders widget. The sticky headers columns update automatically, even with browser resizing, so I'm not sure why this modification is needed.

**Comment by naduda** [comment]
I have dynamical table, wich hide columns after init (for different users -
hide different columns).
I have something like this - if to your example add programical hide
columns in the end of script (after init tablesorter).

As result in your example js will be:
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/* Documentation for this tablesorter FORK can be found at
 * http://mottie.github.io/tablesorter/docs/
 */
$(function () {

    /*** custom css only button popup ***/
    $(".custom-popup").tablesorter({
        theme: 'blue',
        widgets: ['zebra', 'columnSelector', 'stickyHeaders'],
        widgetOptions: {
            // target the column selector markup
            columnSelector_container: $('#columnSelector'),
            // column status, true = display, false = hide
            // disable = do not display on list
            columnSelector_columns: {
                0: 'disable' /* set to disabled; not allowed to unselect it
*/
            },
            // remember selected columns (requires $.tablesorter.storage)
            columnSelector_saveColumns: true,

            // container layout
            columnSelector_layout: '<label><input
type="checkbox">{name}</label>',
            // data attribute containing column name to use in the selector
container
            columnSelector_name: 'data-selector-name',

            /* Responsive Media Query settings */
            // enable/disable mediaquery breakpoints
            columnSelector_mediaquery: true,
            // toggle checkbox name
            columnSelector_mediaqueryName: 'Auto: ',
            // breakpoints checkbox initial setting
            columnSelector_mediaqueryState: true,
            // responsive table hides columns with priority 1-6 at these
breakpoints
            // see
http://view.jquerymobile.com/1.3.2/dist/demos/widgets/table-column-toggle/#Applyingapresetbreakpoint
            // *** set to false to disable ***
            columnSelector_breakpoints: ['20em', '30em', '40em', '50em',
'60em', '70em'],
            // data attribute containing column priority
            // duplicates how jQuery mobile uses priorities:
            //
http://view.jquerymobile.com/1.3.2/dist/demos/widgets/table-column-toggle/
            columnSelector_priority: 'data-priority',

            // class name added to checked checkboxes - this fixes an issue
with Chrome not updating FontAwesome
            // applied icons; use this class name (input.checked) instead
of input:checked
            columnSelector_cssChecked: 'checked'
        }
    });

    $('.tablesorter thead tr:first').find('th').eq(1).css({display: "none"})

     $('.tablesorter tfoot tr:first').find('th').eq(1).css({display:
"none"})

    $('.tablesorter tbody tr').each(function(){
        $(this).find('td').eq(1).css({display: "none"})
    });
});
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2015-05-04 1:16 GMT+03:00 Rob G <notifications@github.com>:

**Comment by Mottie** [comment]
The column selector widget uses css to hide columns, so any changes to the table will automatically be applied; even if the entire tbody is replaced.

If you are using the column selector widget, you can programmically hide columns using the ["refreshColumnSelector" method](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#methods):

```js
// hide column 1 (zero-based index)
$('table').trigger('refreshColumnSelector', [ [1] ]);
```

In the example code shared in the last comment, jQuery is being used to hide the second column. So if the tbody content is replace, the jQuery code used to hide the second column would need to be executed again.

**Comment by naduda** [comment]
ok, thank you for the answer.
But, we have tablesorter (core), add sticky widget, and we must add
selector widjet (when it doesn't need to us). I think this is not very
obviously.

2015-05-05 16:00 GMT+03:00 Rob G <notifications@github.com>:

**Comment by Mottie** [comment]
Can't you just add the following css?

```css
.tablesorter tr th:nth-child(2),
.tablesorter tr td:nth-child(2) {
  display: none;
}
```

Then you don't need any changes to the widget, or any extra code.

**Comment by Mottie** [comment]
You don't need to use the columnSelector widget, just the css to hide the column.

Why does a column even need to be hidden?

**Comment by naduda** [comment]
Yes. Thank you, Rob.
I applay widget dynamicly after create and config table.
In this case all right.

2015-05-07 15:58 GMT+03:00 Rob G <notifications@github.com>:

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Pull request closed without merging**
