### PR TITLE
Ability to sort tables with multiple tbodies

### PR DESCRIPTION
**Pull request by emmerich**
Currently, tables with multiple tbodies can be sorted only within the tbody. That is, the rows inside each body are sorted relative to each other, but bodies remain relatively autonomous.

There's a use case where the user may wish to sort between bodies and either:
  a) sort the rows inside the body too
  b) leave the rows inside each body static, but have the bodies rearrange themselves

The patch supplied adds this functionality through the use of a bodyCache which works in a similar way to the current row cache.

The body cache is computed whenever sorting via bodies is enabled, and composes a cache identical to one "body" entry in the row cache, but spread across multiple bodies. Each "row" entry in the body cache is the normalized values of the "primary row" in each body.

A primary row is defined as a row that supplies the data for each column required for sorting that body.

I've attached some examples as to how to use the new functionality, and I'm fairly sure it remains backwards compatible with existing tablesorter configurations (all other examples still work)

Note: minified file not updated

### CODE REVIEW

**Comment by KennethHooper** [comment]
Hey @Mottie 

I was able to get the table sort to work using your sortTbody widget, but I'm having trouble keeping the TBODY to stay grouped with it's original TR. 

I have unique ID's on each TBODY that must stay with it's content.

See example at http://jsfiddle.net/Lsx2b4ao/

**Comment by Mottie** [comment]
Hi @KennethHooper!

I haven't looked at the tbody sorting widget in a while; a lot has changed since then, so I'll see what I can do. Just give me some time.

**Comment by KennethHooper** [comment]
Sounds great and thanks for looking into this! This widget is fantastic!

K

**Comment by Mottie** [comment]
After looking at the widget, I think it will be possible to make it into a widget; but it'll require some more changes to the tablesorter core. So, sadly, I don't think I'll be able to include it with the next update.

**Comment by KennethHooper** [comment]
Sounds good. Is there any way that I can get the revision before it's rolled into the next update to test?

Thanks!

K

**Comment by prijutme4ty** [comment]
Hey all,
Mottie sent me to read this issue while discussing #820. There are some opposite reasonings to keep common cache for all tbodies or only for info-only tbodies. I am arguing that we should possibly make cache be storing only non-infoOnly tbodies but there may be some consequences with an implementation of tbodySorting. So I want to share some my thoughts about an implementation of tbodySorting.

First, I think it's actually better to implement a feature using widget not to introduce in the core, as Mottie said. And also one should keep in mind that info-only tbodies can have very different markup from usual ones.
That's why I believe, it isn't wise to mix rows with different markup in a single cache. It will introduce lots of conditionals in code in yet unpredictable places. Introducing a separate cache is a much better way, IMO. 
I suggest this cache should be a tiny one, storing only tbody position and extracted content to be compared during sort. I think, it's better not to include tbody content not to introduce unnecessary dependencies (but I'm not sure because don't know JS/jQuery well enough; if tbody elements will be updated automatically on operations, there is no problem to store them too in order to achieve simplier sorting).
It seems there's no problem to calculate this `bodyCache` in a widget, based on information from already existent `cache`. No need to include this new cache into a core.

Moreover, due to differences in markup, I suppose it's a bad idea to use `sortTbody_primaryCell` merely as a selector for content extraction. It can be very restricting. What if information necessary for tbody sorting is included in different kinds of cells for different tbodies or (even more likely) in data-attributes of tbodies. I think `sortTbody_primaryCell` should accept either a function accepting tbody element as an argument. Possibly this option should be either a function or a selector.

@Mottie, @emmerich, @thezoggy, @tb, @KennethHooper, what do you think about it?

**Comment by KennethHooper** [comment]
Hi @Mottie,

Just wanted to see if the Tbody sorting was ever addressed and if I still need to use the sortTbody widget of if this functionality was put into the core?

Thanks again

**Comment by Mottie** [comment]
Hi @KennethHooper!

Sadly, I just haven't had the time to finish work on the tbody sort widget.

Initially I ran into a wall with the way the cache was set up, but that was fixed back in v2.16.0.... now  the problem is that "info-only" tbodies are not parsed, so I would need to add a separate cache for that info before I can even get the sorter to work. It's not that much more work... I just need some free time, and some motivation.

**Comment by KennethHooper** [comment]
Thanks for the update @Mottie,

I'd attempt it myself, but I really don't even know where to begin. I'm trying to finish up my sorting, but unfortunately stuck on this. 

Thanks again!

**Comment by KennethHooper** [comment]
@Mottie,

Another question I have is if this will work with AJAX content in the table? If so, could you explain if there needs to be any additional configuration?

Could I maybe help motivate with a little PP tip?

**Comment by KennethHooper** [comment]
@Mottie,

Just putting a bug in your ear about this to see if you've had an opportunity to look at the tbody sort widget any more.

Thanks!

**Comment by Mottie** [comment]
Hi @KennethHooper!

Sorry, I haven't gotten around to it yet :disappointed:... the scroller widget has been taking up a lot of my free time. It is getting closer to being usable/stable so maybe I'll have some time this weekend to revisit the tbody sorting widget.

**Comment by KennethHooper** [comment]
Rob,
Thanks for the update! 
Let me know if you have anything over the weekend. Is there maybe someway to contribute something to get this part figured out?
I also have to test this in an AJAX environment, so I'm hoping there won't be any more issues. :) Thanks,


Ken Hooper

**Comment by Mottie** [comment]
Hey @KennethHooper!

I haven't completed the documentation for it yet, but I [made a demo](http://jsfiddle.net/Mottie/abkNM/5912/) that you can use to test out your code. I would appreciate it if you would test it using your markup and tell me if you encounter any errors or issues.

If you want to test the widget locally, copy the code from the javascript frame, and make sure to use the most up-to-date tablesorter & widget files.

The only "sorta" issue I've found is in the first table. When you filter a column, the non-primary rows are all hidden. If you filter any text in the non-primary rows in the first column, all rows are hidden except that row; which is the correct behavior, but it "feels" wrong. I could set some of the other filter widget option to ignore child row content.

Anyway, send in the feedback!

**Comment by KennethHooper** [comment]
@Mottie,

Thanks for the hard work an the update. I have a demo at http://jsfiddle.net/m396ywwx/ with the updated widget. Everything seems to be working great!

I'm not using a filter, but I did notice that it hides the non-primary child row when filtered. Not sure what you want to do about that.

Thanks again!

**Pull request closed without merging**
