### PR TITLE
Check that the filter is not undefined before encoding/decoding it.

### PR DESCRIPTION
**Pull request by tim-schilling**
This bug can be reproduced on the [external filter demo page](https://mottie.github.io/tablesorter/docs/example-widget-filter-external-inputs.html). A user needs to type in any valid search value for the external search, then clear it out, then refresh the page. The page will appear, show all the results, then they disappear as the filtering process removes them.

I haven't tried different browsers, operating system or versions of jQuery as I'm pretty sure it's unrelated to those. There is no actual error thrown, it simply clears out the results. I believe this was introduced by commit e2ffab4 as a fix for #1026.

What's happening is that the `processFilters` function expects there to be filters for each of the columns. However, in the case of only using an external filter, there are none. `processFilters` then sets the filter values for the column indexes to be `undefined`. This function then encodes that as a string. The problem is that on the parsing of the storage values, this string is treated as a valid value for the filter. Then the `'undefined'` values for each of the column filters is applied which don't match anything, which essentially clears the table.

It can be undone on the page by forcing a new search to be applied which will then look for new filters and use those. I believe a simple check that the filter is not undefined before setting the encoding/decoding in `processFilters` will fix this problem.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @tim-schilling!

Thanks for contributing! I'll try to take a look at this in more detail in the next few days.

**Comment by Mottie** [comment]
Ok, looks good! Thanks again!

**Comment by tim-schilling** [comment]
Not a problem, thanks for getting around to this so quickly.

**Comment by Mottie** [comment]
I'm not sure when I'll push a new release, so it'll only live in the master branch for now... I'll try not to wait too long though :wink:

**Pull request merged**
