### PR TITLE
Adds really short date formatting. 'mmddyy' Assumes 2015.

### PR DESCRIPTION
**Pull request by billrob**
I know this was removed in the past and I can do, and have done, with a parser.  This is the 5th project in a year I needed to go find my custom parser code and bring it into new project.

Please consider this addition.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @billrob!

Thanks for contributing!

Doesn't the already existing [two-digit-year parser](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-date-two-digit-year.js) not work for you? See [the demo here](http://mottie.github.io/tablesorter/docs/example-parsers-dates.html).

It supports three formats ( "mmddyy", "ddmmyy" and "yymmdd" ) and it looks for a two digit year within a specified range (default is 50 years), so if a table were to list a year as "99", the parser would interpret it as "1999" and not "2099".

Honestly, I would prefer not to add a new parser directly to the core plugin unless it were essential; but if you wanted to submit a parser in a separate file, I would be more open to including it in the project.

**Comment by billrob** [comment]
Hi Mottie, let me take a look.

**Comment by billrob** [comment]
Looks like it would work, however why does the "IS" check always return false?  Isn't that key to getting the parser to do the parsing?

**Comment by Mottie** [comment]
The `is` function is used for when tablesorter initializes and attempts to auto-detect parsers for a column.

When a custom parser is used, you know the contents of the column, so you set the parser for that column by class (e.g. "sorter-myparser") or in the `headers` option (e.g. `headers: { 0: { sorter: 'myparser' } }` ), or using any of the other methods to set the parser.

**Comment by billrob** [comment]
Hi Mottie.  I'll close this request.  I'm looking towards changing the is function on the parse to look for valid date time formats in the 2 year digit.

If I were to change the "two-digit-year" parser, you think that is the best way?

I'm trying to avoid declaring a custom headers/sorter : syntax, so it works across my application automatically for my developers.

**Comment by Mottie** [comment]
I don't think you can detect a 2-digit-year date. If I didn't tell you the date format ("mmddyy", "ddmmyy" or "yymmdd" - see [ref](http://en.wikipedia.org/wiki/Date_format_by_country)) and gave you this date:

    12/11/10

Would you get it right?

If your application only deals with one date format and you don't want that extra step for your developers, then a custom parser would work just fine.

Honestly, I don't think it would be that difficult to include an extra parser (not modify the core) and add `"sorter-mmddyy"` to the column header class name - just to make sure, you are aware that you can define the parser for a column in multiple ways? [Here is a demo](http://mottie.github.io/tablesorter/docs/example-parsers-class-name.html).

**Comment by billrob** [comment]
I have a one in three change of guessing it correctly.  :)

I get your point.  However, if I used the config.dateFormat, I would know what to test for wouldn't I?

**Comment by Mottie** [comment]
Hey @billrob!

Yeah, I guess you're right... you could use the `dateFormat` to get the correct format. I still don't think I'll include this change to the core since it's assuming too much; there is no way to properly set `99` (for 1999) in the date.

A custom parser could easily solve this issue.

**Pull request closed without merging**
