### PR TITLE
clear column container when refreshing

### PR DESCRIPTION
**Pull request by eltharin**
when refreshing plugins, i have all columns in double on the columnselector div.

### CODE REVIEW

**Comment by Mottie** [comment]
Hi @eltharin!

Thanks for your contribution!

Would you share the circumstances of when you see double? I created [this demo](https://jsfiddle.net/Mottie/mcn8o3yu/1/) which triggers an "updateAll" and I don't see double entries in the columnselector div.

**Comment by eltharin** [comment]
Hi

 

When I have Big table to load, I print my table without ligne, i load tablesorter, 

 

After In ajax i get the content of table, put in on the cache : 

 

$.tablesorter.updateCache($(id_div_tableau).get(0).config,function(){},$('<tbody>'+data+'</tbody>'));

 

After i refresh all widgets

 

$(id_div_tableau).trigger('refreshWidgets', true);

 

And at this moment I have all elements duplicated.

 

Maybe it’s not the good way ?

 

Roman JOLY

 

De : Rob G [mailto:notifications@github.com] 
Envoyé : jeudi 28 janvier 2016 14:30
À : Mottie/tablesorter <tablesorter@noreply.github.com>
Cc : eltharin <eltharin18@hotmail.fr>
Objet : Re: [tablesorter] clear column container when refreshing (#1145)

 

Hi @eltharin <https://github.com/eltharin> !

Thanks for your contribution!

Would you share the circumstances of when you see double? I created this demo <https://jsfiddle.net/Mottie/mcn8o3yu/1/>  which triggers an "updateAll" and I don't see double entries in the columnselector div.

**Comment by Mottie** [comment]
Ahh, yes... the tbodies parameter in the [`updateCache` method](http://mottie.github.io/tablesorter/docs/#updatecache) is supposed to be a jQuery selector pointing to tbodies. In the docs, you'll see this message:

> In v2.22.2, a new parameter was added to allow passing a jQuery object containing tbodies (for the tbody sorting widget)

I'll fix the wording, but in your case don't include that extra parameter.

**Comment by eltharin** [comment]
I’m using this method beacause i have a 5000’s lignes table and it’s a « little » long to load before in a navigator and then load the pager.

 

Roman JOLY

 

De : Rob G [mailto:notifications@github.com] 
Envoyé : jeudi 28 janvier 2016 14:43
À : Mottie/tablesorter <tablesorter@noreply.github.com>
Cc : eltharin <eltharin18@hotmail.fr>
Objet : Re: [tablesorter] clear column container when refreshing (#1145)

 

Ahh, yes... the tbodies parameter in the  <http://mottie.github.io/tablesorter/docs/#updatecache> updateCache method is supposed to be a jQuery selector pointing to tbodies. In the docs, you'll see this message:

In v2.22.2, a new parameter was added to allow passing a jQuery object containing tbodies (for the tbody sorting widget)

I'll fix the wording, but in your case don't include that extra parameter.

**Comment by Mottie** [comment]
Ok, if you want to use that parameter, and everything else works for you, then I don't have a problem with this PR :grin:

**Comment by Mottie** [comment]
Hmm, whoops, that actually causes an error.

**Comment by Mottie** [comment]
Ok, that should fix the problem... I saw that error when I used `$('table').trigger('refreshWidgets');` and the remove function is called on tables that don't have the column selector applied.

**Pull request merged**
