### PR TITLE
Ignore unnecessary exported files in distributed package

### LINKED ISSUE #1731: Install via Composer only the subfolder /dist with JS and CSS files
In the documentation you don't have any info on installing Tablesorter via composer, only via npm, it would be awesome to add it.
Also, installing via Composer installs the full repo, would be great to add only the /dist subfolders (js and css) as it happens with the npm install.

Thanks for your great software :)

Related to #1355

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Fix #1731

### CODE REVIEW

**Comment by Mottie** [comment]
Thanks! Sorry for taking so long to get back to this PR!

I don't know when I'll have time to update the repo and update the npm package though 😿

**Comment by pedro-mendonca** [comment]
Thanks 👍

**Comment by pedro-mendonca** [comment]
Hi @Mottie,

Are you planning to include this in a release anytime soon?

Thanks in advance :-)

**Comment by Mottie** [comment]
Ooof, sorry, I haven't looked at tablesorter in quite some time. I think I had a bunch of stuff in the works, but didn't finish any of it. Let me review again this coming weekend.

**Pull request merged**
