### PR TITLE
Fix multiple tbodies cache

### PR DESCRIPTION
**Pull request by prijutme4ty**
Duplicate of #820 but against 'working' branch.

### CODE REVIEW

**Comment by TheSin-** [comment]
do make this a clean merge you need to change all instances of `getElementText` to `ts.getElementText` in js/jquery.tablesorter.js once that is done I can merge this I was going to do it but then I'll loose all these comments since it'll look like I made the patch, I'd rather keep the integrity.

**Comment by prijutme4ty** [comment]
Will rebase it soon against updated working branch

**Comment by TheSin-** [comment]
perfect thank you.

**Comment by prijutme4ty** [comment]
Sorry for a delay. Rebased now

**Comment by Mottie** [comment]
Thanks @prijutme4ty for going through all that extra trouble!

I'm going to start following @TheSin- 's advice and start making changes in the master branch and get rid of the working branch. It makes merging easier and we won't have to go through all these extra steps in the future.

**Pull request merged**
